# Generated by Django 5.2.1 on 2025-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_consulta_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Fractura', 'Fractura'), ('General', 'General'), ('Internista', 'Internista'), ('Dermatólogo', 'Dermatólogo'), ('Pediatría', 'Pediatría')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_afiliacion',
            field=models.CharField(choices=[('contributivo', 'Contributivo'), ('subsidiado', 'Subsidiado')], max_length=50),
        ),
    ]
