# Generated by Django 5.2.1 on 2025-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medico_direccion_medico_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
