# Generated by Django 5.2.1 on 2025-05-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_medico_direccion_alter_medico_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='unidad',
        ),
    ]
