# Generated by Django 5.2.1 on 2025-05-27 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_medico_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='unidad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medico'),
        ),
    ]
