# Generated by Django 5.2.1 on 2025-05-27 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paciente_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='core.medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Fractura', 'Fractura'), ('General', 'General'), ('Internista', 'Internista'), ('Dermatólogo', 'Dermatólogo'), ('Pediatría', 'Pediatría')], max_length=100, null=True),
        ),
    ]
